# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20170417_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='zapato',
            name='title',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
